from flask import Flask, request, send_file, jsonify
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from flask_cors import CORS
import cv2
import numpy as np
from waitress import serve

app = Flask(__name__)
CORS(app)

# Function to determine the season based on RGB
def get_season(rgb):
    r, g, b = rgb

    if r > g and r > b:  # Warm colors
        if g > b:
            return "Spring", ["Peach", "Coral", "Mint Green"], ["Cool Blues", "Deep Reds"]
        else:
            return "Autumn", ["Mustard", "Olive Green", "Rust"], ["Cool Blues", "Pinks"]
    else:  # Cool colors
        if g > r:
            return "Summer", ["Pastel Blue", "Lavender", "Soft Gray"], ["Bright Orange", "Warm Yellow"]
        else:
            return "Winter", ["Deep Blue", "Burgundy", "Black"], ["Warm Beige", "Soft Browns"]

@app.route('/generate-pdf', methods=['POST'])
def generate_pdf():
    if 'image' not in request.files:
        return jsonify({"error": "No image uploaded"}), 400

    file = request.files['image']
    file_path = "temp.jpg"
    file.save(file_path)

    dominant_color = get_dominant_color(file_path)
    season, best_colors, avoid_colors = get_season(dominant_color)

    pdf_path = "color_analysis.pdf"
    c = canvas.Canvas(pdf_path, pagesize=letter)

    # 🖼️ Header
    c.setFont("Helvetica-Bold", 20)
    c.drawString(180, 770, "✨ Color Analysis Report ✨")
    
    # 🎨 Dominant Color Box
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, 720, f"Your Dominant Color:")
    c.setFillColorRGB(dominant_color[0] / 255, dominant_color[1] / 255, dominant_color[2] / 255)
    c.rect(250, 710, 50, 30, fill=True, stroke=False)

    # 🍂 Season
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, 680, f"Your Season: {season}")

    # ✅ Best Colors
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, 640, "✅ Best Colors to Wear:")
    for i, color in enumerate(best_colors):
        c.setFont("Helvetica", 12)
        c.drawString(120, 620 - (i * 20), f"- {color}")

    # ❌ Colors to Avoid
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, 550, "❌ Colors to Avoid:")
    for i, color in enumerate(avoid_colors):
        c.setFont("Helvetica", 12)
        c.drawString(120, 530 - (i * 20), f"- {color}")

    # 🌈 Color Palette Preview
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, 470, "🌈 Suggested Color Palette:")
    palette_x = 120
    for i, color in enumerate(best_colors):
        c.setFillColorRGB(0.2 + i * 0.2, 0.5, 0.8)  # Fake colors, adjust later
        c.rect(palette_x, 450, 40, 20, fill=True, stroke=True)
        palette_x += 50

    # 📌 Footer
    c.setFont("Helvetica", 10)
    c.drawString(100, 50, "Generated by the Color Analysis App - Enhance your style!")

    c.save()
    return send_file(pdf_path, as_attachment=True, mimetype='application/pdf')

def get_dominant_color(image_path):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    pixels = np.float32(image.reshape(-1, 3))

    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
    _, labels, palette = cv2.kmeans(pixels, 3, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)
    
    dominant_color = palette[np.argmax(np.bincount(labels.flatten()))]
    return [int(c) for c in dominant_color]  # Convert to integers


if __name__ == '__main__':
    serve(app, host="0.0.0.0", port=5000)

